# =====================================================================
# HYPRLAND CONFIG - PIXEL-ART TECH / CYBER-HUD EDITION
# =====================================================================

# --- AUTIOSTART ---
exec-once = ~/.config/scripts/autostart.sh

# --- MONITORES ---
monitor=,preferred,auto,1

# --- VARIABLES DE ENTORNO ---
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct

# --- TECLA MAESTRA ---
$mainMod = SUPER

# --- ESTÉTICA Y GEOMETRÍA ---
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgb(ff3333) rgb(ffffff) 45deg # Acentos Rojo y Blanco
    col.inactive_border = rgb(001c48)                 # Azul profundo base
    layout = dwindle
}

decoration {
    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 2
        new_optimizations = true
        ignore_opacity = true
    }
    drop_shadow = yes
    shadow_range = 15
    shadow_render_power = 3
    col.shadow = rgba(001c48aa)
}

# --- SMART GAPS (Optimización Pantalla Única) ---
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]

# --- REGLAS ANTI-INTERRUPCIÓN (Juegos) ---
windowrulev2 = idleinhibit focus, fullscreen:1

# --- ATAJOS DE TECLADO ---
bindr = $mainMod, SUPER_L, exec, pkill rofi || rofi -show drun -theme ~/.config/rofi/config.rasi
bind = $mainMod, T, exec, kitty
bind = $mainMod, Q, killactive, 
bind = $mainMod, F, fullscreen, 
bind = $mainMod, V, togglefloating, 

# Gestión de ventanas (Layout y Foco)
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Alternar Maximizar (Focus sin cerrar el resto)
bind = $mainMod, M, fullscreen, 1

# Filtros Nocturnos
bind = $mainMod, N, exec, hyprshade toggle blue-light-filter
bind = $mainMod SHIFT, N, exec, hyprshade toggle grayscale

# Capturas de Pantalla
bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -
bind = $mainMod, Print, exec, wf-recorder -f ~/Videos/recording.mp4

# Toggle Modo Hacker / Trabajo Limpio
bind = $mainMod, Escape, exec, ~/.config/scripts/toggle_widgets.sh

# Perfiles de Energía (Ventiladores)
# Modo silencioso ideal para certámenes de programación en Java
bind = $mainMod SHIFT, P, exec, powerprofilesctl set power-saver
bind = $mainMod, P, exec, powerprofilesctl set performance
